# Backend service definition

services:
  backend:
    build:
      context: ../ushadow/backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-backend
    env_file:
      - ../.env          # Environment configuration
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      # Server configuration
      - HOST=0.0.0.0
      - PORT=8000  # Internal port - always 8000
      - BACKEND_PORT=${BACKEND_PORT:-8000}  # External port - uses offset from .env
      - REDIS_URL=redis://redis:6379/${REDIS_DATABASE:-0}
      # Tailscale IP for node registration (set via .env or detected)
      - TAILSCALE_IP=${TAILSCALE_IP:-}
      # Tailscale container name for peer discovery (docker exec)
      - TAILSCALE_CONTAINER=tailscale
      # Host project root for docker compose volume mounts (required for service management)
      - PROJECT_ROOT=${PROJECT_ROOT:-${PWD}}
      # Compose project name for per-environment Tailscale containers
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-ushadow}
      - MONGODB_DATABBASE=${MONGODB_DATABASE:-ushadow}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,http://localhost:3000,http://localhost:${WEBUI_PORT}}
    volumes:
      - ../ushadow/backend:/app
      - ../config:/config  # Mount config directory (read-write for feature flags)
      - ../compose:/compose  # Mount compose files for service management
      - /app/__pycache__
      - /app/.pytest_cache
      # Docker socket for container management (Tailscale container control)
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

networks:
  infra-network:
    name: infra-network
    external: true
