# Chronicle backend service definition with sidecar workers
# Environment variables are passed directly via docker compose subprocess env
# No .env files needed - CapabilityResolver provides all values

# =============================================================================
# USHADOW METADATA (ignored by Docker, read by ushadow backend)
# =============================================================================
x-ushadow:
  # Services share namespace with main ushadow for unified auth (AUTH_SECRET_KEY)
  chronicle-backend:
    display_name: "Chronicle"
    description: "AI-powered voice journal and life logger with transcription and LLM analysis"
    requires: [llm, transcription]
    optional: [memory]  # Uses memory if available, works without it
  chronicle-webui:
    display_name: "Chronicle Web UI"
    description: "Web interface for Chronicle voice journal"
    requires: []

services:
  chronicle-backend:
    image: ghcr.io/ushadow-io/chronicle-backend:auth-fix
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-chronicle-backend
    # Sidecar mode: Run both workers and backend in same container
    command:
      - /bin/bash
      - -c
      - |
        echo "🚀 Starting Chronicle with sidecar workers..."
        ./start-workers.sh &
        sleep 3
        echo "🌐 Starting FastAPI backend..."
        exec uv run --extra deepgram python src/advanced_omi_backend/main.py
    ports:
      - "${CHRONICLE_PORT:-8080}:8000"
    environment:
      # Infrastructure connections (from CapabilityResolver or defaults)
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      - QDRANT_BASE_URL=${QDRANT_BASE_URL:-http://qdrant:6333}
      - QDRANT_PORT=${QDRANT_PORT:-6333}

      # LLM capability (from selected provider) - REQUIRED
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}

      # Transcription capability (from selected provider)
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY:-}
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER:-deepgram}
      # Memory capability (optional, from selected provider)
      - MEMORY_SERVER_URL=${MEMORY_SERVER_URL:-}

      # Security (from settings) - AUTH_SECRET_KEY is required for JWT auth
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
      - ACCEPTED_ISSUERS=${ACCEPTED_ISSUERS:-ushadow}
      # CORS
      - CORS_ORIGINS=${CORS_ORIGINS:-*}

    volumes:
      # Data persistence
      - chronicle_audio:/app/audio_chunks
      - chronicle_data:/app/data
      - chronicle_debug:/app/debug_dir

      # Model registry - defines available LLMs, embeddings, STT, TTS
      # Uses PROJECT_ROOT env var for host path (set by backend container)
      - ${PROJECT_ROOT}/config/config.yml:/app/config.yml:ro

    networks:
      - infra-network

    # NOTE: Depends on shared infrastructure services (mongo, redis, qdrant)
    # These must be started separately via docker-compose.infra.yml
    # Cannot use depends_on for services in external compose files

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/readiness"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  chronicle-webui:
    image: ghcr.io/ushadow-io/chronicle-webui:${CHRONICLE_IMAGE_TAG:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-ushadow}-chronicle-webui
    ports:
      - "${CHRONICLE_WEBUI_PORT:-3080}:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:${CHRONICLE_PORT:-8080}
      - BACKEND_URL=http://chronicle-backend:8000
    networks:
      - infra-network
    depends_on:
      - chronicle-backend
    restart: unless-stopped

# Chronicle data volumes (local to this environment)
volumes:
  chronicle_audio:
    driver: local
  chronicle_data:
    driver: local
  chronicle_debug:
    driver: local

# Use existing shared infrastructure network
networks:
  infra-network:
    name: infra-network
    external: true
