# Development override - Vite dev server with hot-reload
# Usage: docker compose -f docker-compose.yml -f compose/overrides/dev-webui.yml up

services:
  webui:
    build:
      context: ./ushadow/frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "${WEBUI_PORT:-3000}:5173"
    volumes:
      - ./ushadow/frontend/src:/app/src:delegated
      - ./ushadow/frontend/public:/app/public:delegated
      - ./ushadow/frontend/index.html:/app/index.html:ro
      - ./ushadow/frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./ushadow/frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./ushadow/frontend/tsconfig.node.json:/app/tsconfig.node.json:ro
      - ./ushadow/frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./ushadow/frontend/postcss.config.js:/app/postcss.config.js:ro
    environment:
      - VITE_HMR_PORT=${WEBUI_PORT:-3000}
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
